### PR TITLE
Chaeng/reflection

### PR DESCRIPTION
**Pull request by Chaeng**
Update the shader caller.

### CODE REVIEW

**Comment by achekery** [comment]
@Chaeng 
You have "SecondaryRay.meta".  Did you mean to also update "SecondaryRay.cs"?

Edit -- Not a problem, since Joe explained

**Comment by achekery** [comment]
@Chaeng 
`Does the shader compile?  I see Reflection.compute has total 4 open comment tokens "/*" and total 3 close comment tokens "*/".`

**Comment by achekery** [comment]
To update the review, just commit your local changes and push the same branch again

**Comment by joeccleung** [comment]
> @Chaeng
> You have "SecondaryRay.meta". Did you mean to also update "SecondaryRay.cs"?

I guess it was the folder called "SecondaryRay" under "RenderPipeline"

**Review by joeccleung — APPROVED** [review]

**Review by kaihuh — APPROVED** [review]

**Pull request closed without merging**
