### PR TITLE
[Scene] Support parsing a sphere from Unity Scene to Compute Shader

### PR DESCRIPTION
**Pull request by joeccleung**
The geometry type is stored in RTGeometryType.cs
The geometry base class is RTGeometry.cs
The sphere class is RTSphere.cs. It defines the sphere.

The RTSphereRenderer supports Rendering Pipeline by relaying the sphere information.

The SRP is responsible for setting the sphere data to compute shader.

### CODE REVIEW

**Comment by achekerylla** [comment]
Are we updating SLN file for new source code files?  I only see the following files associated so far

**Comment by achekerylla** [comment]
image

**Comment by achekerylla** [comment]
Never mind, looks like these are auto gen by Unity.  New for me.

**Comment by achekery** [comment]
Seeing this Error on Unity Project Load.

```
Compute shader (RayTracing.compute): Property (_Spheres) at kernel index (0) is not set
UnityEngine.ComputeShader:Dispatch()
RayTracingRenderPipeline:RenderPerCamera(ScriptableRenderContext, Camera) (at Assets/RenderPipeline/RayTracingRenderPipeline.cs:109)
RayTracingRenderPipeline:Render(ScriptableRenderContext, Camera[]) (at Assets/RenderPipeline/RayTracingRenderPipeline.cs:41)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
```

Was this fixed on a separate review?

**Comment by joeccleung** [comment]
Fixed in another Pull Request

**Pull request closed without merging**
