### PR TITLE
[Materials] Add material parsing, need compute integ

### PR DESCRIPTION
**Pull request by achekery**
Tested with all scenes.  No graphic glitches or unusual behavior.

To use material parsing
(1) Like in AndrewScene, add MaterialDatabase with Material objects.  Give them values. Name them uniquely.
(2) Modify your shapes to Name the material they will use.

Need compute shader integration
(1) Already I added _NumOfMaterials and _Materials as parameters to compute functions.
(2) Already I added example how to use this:

    // Example of how to retrieve material info
    RTMaterial mat = GetIndexedMaterial(hit.matIndex,
        numOfMaterials, materials);
    float shininess = mat.n;

### CODE REVIEW

**Comment by achekery** [comment]
Todo (nice to have, for later, if we have time) - Add default material to be auto selected when material index is invalid (i.e. Name didn't match any material, for now this range checking is manual). Add more example materials in AndrewScene. 

Done - Encapsulate code into utility function.

**Comment by achekery** [comment]
SceneParser not branching into GetMaterials. The count is zero? Why

**Comment by achekery** [comment]
Debug.Log helps troubleshoot, like printf

**Comment by achekery** [comment]
Dont use awake function, we want this to work without play mode. OnEnable?

**Comment by achekery** [comment]
@joeccleung , @Chaeng , @kaihuh  - Please review.  This is updated to fix the bug Joe helped me to find.

**Review by joeccleung — COMMENTED** [review]
good

**Pull request merged**
